context:
  version: "2.2.0"

package:
  name: some-sass-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/some-sass-language-server/-/some-sass-language-server-${{ version }}.tgz
  sha256: f6ed7b4e8155caf766a4b389a5d4e704b1533a496022091a030ef8b43f0f4871

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - some-sass-language-server --node-ipc

about:
  license: MIT
  license_file: LICENSE
  summary: Modern SCSS language server.
  homepage: https://github.com/wkillerud/some-sass
  repository: https://github.com/wkillerud/some-sass

extra:
  recipe-maintainers:
    - danielnachun
