context:
  version: "2.3.8"

package:
  name: some-sass-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/some-sass-language-server/-/some-sass-language-server-${{ version }}.tgz
  sha256: 75334cd4c05be512f0c924cc6595af1edc25a6849d9514271ba873698a555dac

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - some-sass-language-server --node-ipc

about:
  license: MIT
  license_file: LICENSE
  summary: Modern SCSS language server.
  homepage: https://github.com/wkillerud/some-sass
  repository: https://github.com/wkillerud/some-sass

extra:
  recipe-maintainers:
    - danielnachun
