context:
  version: "2.1.1"

package:
  name: some-sass-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/some-sass-language-server/-/some-sass-language-server-${{ version }}.tgz
  sha256: cd1407f5a425983b2df6f33491b4defebfbd64fc2c8a888660a7ecb83e219df7

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - some-sass-language-server --node-ipc

about:
  license: MIT
  license_file: LICENSE
  summary: Modern SCSS language server.
  homepage: https://github.com/wkillerud/some-sass
  repository: https://github.com/wkillerud/some-sass

extra:
  recipe-maintainers:
    - danielnachun
